### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by alex-place**
I updated the readme to match the current implementation.

### CODE REVIEW

**Comment by rithms** [comment]
There's two other examples you missed. :wink: 

The current stable release is v3.9. Because of this, I think the README should remain the way it is for now, even though the master branch contains the alpha version v4.0.

There are examples included in the master branch for v.40 for users that want to compile and use v4.0.

I will merge this PR when we release v4.0 if you update the other examples as well.

**Comment by rithms** [comment]
Things that need to be changed before this can be merged:

1.) You removed an example with no explanation as to why.
2.) Your PR includes a commit that adds setters to the Summoner DTO.

I assume #2 is in response to your issue - https://github.com/rithms/riot-api-java/issues/69
which is fine, I just ask you separate it into it's own PR.

Thanks.

**Comment by alex-place** [comment]
Yeah that was something Github did on it's own. Sorry I'm not used to working on a fork. You can grab the updated readme from my fork. I'm not sure how to seperate the PR.

**Comment by rithms** [comment]
Derp. Righto!

**Comment by alex-place** [comment]
Anyways I'm closing this PR as I've already screwed it up, if you could take what's in my fork and use that for the readme (whenever your ready) this time I will make sure to send in better PR's in the future.

**Pull request closed without merging**
