### PR TITLE
null pointer fix on champData arg

### PR DESCRIPTION
**Pull request by manuvaldes**
champData != null is failing for me on android API 21 JDK 1.8. Haven't been able to test this proposed fix because Android Studio is a piece of ****.

Manu

### CODE REVIEW

**Comment by rithms** [comment]
Thanks. I'll test and merge later tonight when I get to a computer to do so.

**Comment by rithms** [comment]
Okay, I don't know what method you were using, and what parameters, but this should fix the problem.

Tests - 
**api.getDataChampion(Region.NA, 1, null, null, false, ChampData.IMAGE, ChampData.LORE);**
**api.getDataChampion(Region.NA, 1, null, null, false, ChampData.IMAGE);**
**api.getDataChampion(Region.NA, 1, null, null, false, (ChampData) null);**
**api.getDataChampion(Region.NA, 1, null, null, false, (ChampData) null, null);**
**api.getDataChampion(Region.NA, 1, null, null, false, null, null);**
**api.getDataChampion(Region.NA, 1);**
---------------------
SUCCESSFUL


--------------------------------

I have also added this change to the other Static Data methods that allow multiple parameters. 

Thanks for the contribution, it is greatly appreciated. :)

**Comment by manuvaldes** [comment]
yeah, sorry about the poor documentation, it was almost 2 am and I swear I was about to uninstall android studio xD

Anyway, it's working ok on my end, thanks for such a quick merge!

**Comment by manuvaldes** [comment]
Hi again, this was nagging me, but the fix is not quite correct, because varargs are a bitch. regarding paramenter champData, what the method will see is a ChampData[]

1 If passed as null (no cast), the method will see null (as originally coded).
2 If passed as (ChampData) null, the method will see ChampData[] { null}, an array of size  0 with champData[0] = null (this is the intended fix)
3 If nothing is passed, the method will see Champdata[] {}, an array of length 0.

I believe the current check is problematic: it's not complete for case 2, since you might want to pass, {null, ChampData.IMAGE}, and this would not parse the IMAGE param. And also cases 1 and 3 would fail, with nullpointerexception and arrayindexoutofboundsexception respectively.

So, what should the test look like if we want to support developers  getthe 3 cases? I believe something like this:

if (champData == null || champData.length == 0 || ((champData.length ==1) && (champData[0] == null)) {
 // do nothing
} else {
// do something
}

be aware that we need to test this way because we need operator shortcircuiting (test length only if champdata is not null, check first element  only if length is not zero).

as I said, varargs are a bitch.

**Comment by rithms** [comment]
Yeah. varargs are a real bitch. I came across this issue when fixing the initial problem. 

I thought champData[0] != null would be good enough, because who is really going to pass in (null, ChampData.IMAGE......)?

I will update it to be 100% correct in the next release.

**Pull request merged**
