### PR TITLE
JavaDoc, Optimizations & Clean Up

### PR DESCRIPTION
**Pull request by Linnun**
# JavaDoc
###### Finalized my JavaDoc rework of RiotApi.java
- Every method now has updated, detailed JavaDoc descriptions
- Fixed some methods having invalid JavaDoc (refering to wrong classes or parameters)
- The class itself now has proper JavaDoc, using @author and @version. Please note that @version has to be updated on future version updates. If you permit, 'big' contributors could now add themselves as additional @author of the API

# 5 New Methods
###### Added new methods to allow summonerId input as String instead of long. I did this because many other methods already offered this, and these were missing that option.
- getTeamsBySummonerId(Region, String)
- getTeamsBySummonerId(String)
- getCurrentGameInfo(PlatformId, String)
- getRecentGames(Region, String)
- getRecentGames(String)

# Internal Code Changes
###### I tried to optimize and simplify a few procedures. With the API often being used in a multi-threaded environment for millions of calls in a single instance, even small improvements can sum up to notable improvements in performance and/or resource usage
- Optimized many methods in the individual Apis, by having duplicate methods use each other (for methods which existed for *String summonerId* and *long summonerId*)
- Optimized *Util.Convert.longToString()* with a new algorithm that uses a StringBuilder
- Added @Override toString() methods to the Constant classes to simplify usage
- RiotApi.java no longer passes *String endpoint* to the individual Apis (the endpoint is now gained by calling *region.getEndpoint()*)
- RiotApi.java now gives *Region region* (instead of *String region*) to the individual Apis (with Region now having a proper toString() method, and *Region.getEndpoint()* now returning the regionalized endpoint (unless calling *Region.getEndpoint(false)*) things are really simple now.
- RiotApi.java now gives *Season season* (instead of *String season*) to the StatsApi (like with the region change, toString() makes things really easy)

###### Some words...
GitHub will probably show a conflict in the automatic merge of this pull request because some of these files (especially RiotApi.java with all those JavaDoc and method changes) had some really major changes. As of right now it would be safe to simply overwrite the affected files though, since I used an up-to-date fork of this Api.
I already did alot of testing to avoid any errors, but it can't hurt to double-check that.

### CODE REVIEW

**Comment by rithms** [comment]
> If you permit, 'big' contributors could now add themselves as additional @author of the API

Feel free to add yourself as an author. 
This goes for any contributor. I have no problem with people adding themselves as authors to the project if they contributed.

You're a huge contributor to this project, so much that I wanted to ask you if you wanted to be added as a collaborator of this repo?

**Comment by Linnun** [comment]
> You're a huge contributor to this project, so much that I wanted to ask you if you wanted to be added as a collaborator of this repo?

Thanks for that offer! I gladly accept your offer and will try my best to keep this API up-to-date and working.
Infact I use this API for several backend applications in a project with a few million daily user requests, so it's in my best interest to keep this project alive and kicking :+1:

**Comment by rithms** [comment]
Awesome! Your site is LolSkill right?

I went ahead and added you as a collaborator the repo, so you have push access and stuff.
You can add yourself as an @author. I was going to do it, but I wasn't sure how you wanted it to be typed out.

Thanks for updating the java docs, optimizing the code, and the overall clean up, I really appreciate it.
Didn't realize I was appending Strings in a loop without StringBuilder in that conversion function... T-T oops...

-------------------------------------------

I'm going to go ahead and consider your last two pull requests as a minor patch. So the version will now be 3.7.0, since your last pull request changed the name of the Master and Challenger league functions, which might break some developers existing code. That way developers still using 3.6x can know they will need to update their code to use 3.7.0.

**Comment by Linnun** [comment]
Yep, I'm the CEO of LoLSkill.
I'll add the @author with the next 'natural' commit, no need to rush this change.

3.7.0 sounds appropriate for this version.

By the way, with which Java version do you compile things? Just so I don't use Java 8 features if you're still trying to be compatible with Java 7 or even 6.

**Comment by rithms** [comment]
Java 8

**Comment by Linnun** [comment]
Oh, you're already up for Java 8, awesome! Then I can use simpler ways to convert data :)

Please make sure you can compile the Api with the latest change. You may also want to specify the requirement of Java 8 in the readme.

**Comment by rithms** [comment]
I'll list it as a requirement in the README on the next commit.

**Comment by rithms** [comment]
Oops nvm looks like u already did it 👍

**Pull request merged**
