### PR TITLE
Added tons of JavaDoc, fixed getDataChampion(), renamed 2 methods & added a new constructor

### PR DESCRIPTION
**Pull request by Linnun**
- New: Added detailed JavaDoc for static data methods, status methods,
featured game methods and current game methods
- Fix: Removed parameter "dataById" from "getDataChampion" methods (this
isn't supported for getDataChampion, only for getDataChampionList!)

### CODE REVIEW

**Comment by Linnun** [comment]
Updated with the following additional changes:
- New: Added constructor RiotApi(Region region) to set region without key
- Change: Renamed getChallengerLeagues to getChallengerLeague and getMasterLeagues to getMasterLeague (for clarity, because they return a single League)
- Improved: Added/Updated JavaDocs for all league-related methods
- Fix: Fixed some JavaDocs refering to wrong objects

**Comment by rithms** [comment]
Out of curiosity, what would be the point of a RiotApi object without a key? You wouldn't be able to make API calls.

**Comment by Linnun** [comment]
Good question. Question goes back to you though, since there already is a parameter-less RiotApi() constructor.

I just felt like this version of constructor was missing, when I saw the 3 existing constructors.

**Comment by rithms** [comment]
Hm, true. I guess that's just there if for some reason someone wants to do:

RiotApi api = new RiotApi();
api.setRegion(Region.NA);
api.setKey("API-Key");

for whatever reason.

I guess adding a constructor with just a region would add to this flexibility.
I think my original idea when adding those constructors was to just give more people control on how they wanted to write their code.

**Comment by Linnun** [comment]
Random example to make the new constructor seem not totally useless. I don't think anyone will ever do this :laughing: 

    RiotApi api = new RiotApi(Region.EUW);
    String endpoint = api.getEndpoint();
    manuallyDoStuffWithEndpoint(endpoint);

**Pull request merged**
